### PR TITLE
Gull ms edits

### PR DESCRIPTION
**Pull request by gully**
A few ideas/edits for the paper.

### CODE REVIEW

**Comment by gully** [comment]
Here's the Makefile I was using:

```Makefile
all: ms.pdf

%.pdf: %.tex
	pdflatex $<
	pdflatex $<
	bibtex ms
	pdflatex ms
	pdflatex ms
	rm -rf *Notes.bib
	rm -rf *.log
	rm -rf *.bbl
	rm -rf *.aux
	rm -rf *.blg
	rm -rf *.dvi
```

**Comment by mirca** [comment]
@gully awesome, thanks Gully! Let me know whether I should await or merge this now!

**Comment by gully** [comment]
I recommend spot-checking the manuscript changes, and deciding whether to accept/reject individual changes.  Also the travis-ci fails because I've inserted references but commented-out the bibliography.  You might need to add a local `apj.bst` file to get things to work locally (and on Travis?). I'm often confused by .bst files and do trial and error until they work...

**Comment by mirca** [comment]
👍

**Comment by mirca** [comment]
I rebased this branch in order to get rid of conflicts... merging in 3, 2, 1....

**Pull request merged**
